export type WatchItem = {
  id: string;
  userId: string;
  title: string;
  type: 'movie' | 'show';
  status: 'want-to-watch' | 'watching' | 'finished';
  currentSeason: number | null;
  totalSeasons: number | null;
  rating?: number | null;
  notes?: string | null;
  createdAt: Date;
  updatedAt: Date;
  tmdbId?: number | null;
  tmdbPosterPath?: string | null;
  tmdbOverview?: string | null;
  tmdbTagline?: string | null;
  tmdbImdbId?: string | null;
  tmdbMovieRuntime?: number | null;
  tmdbMovieReleaseYear?: number | null;
  tmdbMovieCertification?: string | null;
  tmdbTvFirstAirYear?: number | null;
  tmdbTvLastAirYear?: number | null;
  tmdbTvNetworks?: string | null;
  tmdbTvNumberOfEpisodes?: number | null;
  tmdbTvNumberOfSeasons?: number | null;
  tmdbTvStatus?: string | null;
  tmdbTvCertification?: string | null;
};