import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';

async function getUserId() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: Record<string, unknown>) {
          cookieStore.set({ name, value, ...options });
        },
        remove(name: string, options: Record<string, unknown>) {
          cookieStore.delete({ name, ...options });
        },
      },
    }
  );
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error || !user) {
    throw new Error('Not authenticated');
  }
  return user.id;
}

export async function GET(_request: NextRequest) {
  try {
    const userId = await getUserId();

    // Get or create notification preferences for the user
    let preferences = await prisma.notificationPreferences.findUnique({
      where: { userId },
    });

    // If no preferences exist, create default ones
    if (!preferences) {
      try {
        preferences = await prisma.notificationPreferences.create({
          data: {
            userId,
            emailEnabled: true,
            welcomeEmailSent: false,
            weeklyDigestEnabled: false,
            monthlyDigestEnabled: false,
            newSeasonAlerts: true,
            friendActivityAlerts: true,
            // unsubscribeToken will be auto-generated by Prisma if field exists
          },
        });
      } catch (error: unknown) {
        // If monthlyDigestEnabled field doesn't exist yet, create without it
        if (error instanceof Error && error.message?.includes('monthlyDigestEnabled')) {
          preferences = await prisma.notificationPreferences.create({
            data: {
              userId,
              emailEnabled: true,
              welcomeEmailSent: false,
              weeklyDigestEnabled: false,
              newSeasonAlerts: true,
              friendActivityAlerts: true,
              // unsubscribeToken will be auto-generated by Prisma if field exists
            },
          });
        } else {
          throw error;
        }
      }
    }

    return NextResponse.json({ preferences });
  } catch (error) {
    console.error('Error fetching notification preferences:', error);
    return NextResponse.json(
      { error: 'Failed to fetch notification preferences' },
      { status: 500 }
    );
  }
}

export async function PUT(request: NextRequest) {
  try {
    const userId = await getUserId();

    const body = await request.json();
    const { 
      emailEnabled,
      weeklyDigestEnabled,
      monthlyDigestEnabled,
      newSeasonAlerts,
      friendActivityAlerts 
    } = body;

    // Update or create notification preferences for the user
    let preferences;
    try {
      preferences = await prisma.notificationPreferences.upsert({
        where: { userId },
        update: {
          emailEnabled,
          weeklyDigestEnabled,
          monthlyDigestEnabled,
          newSeasonAlerts,
          friendActivityAlerts,
          updatedAt: new Date(),
        },
        create: {
          userId,
          emailEnabled: emailEnabled ?? true,
          welcomeEmailSent: false,
          weeklyDigestEnabled: weeklyDigestEnabled ?? false,
          monthlyDigestEnabled: monthlyDigestEnabled ?? false,
          newSeasonAlerts: newSeasonAlerts ?? true,
          friendActivityAlerts: friendActivityAlerts ?? true,
        },
      });
    } catch (error: unknown) {
      // If monthlyDigestEnabled field doesn't exist yet, update without it
      if (error instanceof Error && error.message?.includes('monthlyDigestEnabled')) {
        preferences = await prisma.notificationPreferences.upsert({
          where: { userId },
          update: {
            emailEnabled,
            weeklyDigestEnabled,
            newSeasonAlerts,
            friendActivityAlerts,
            updatedAt: new Date(),
          },
          create: {
            userId,
            emailEnabled: emailEnabled ?? true,
            welcomeEmailSent: false,
            weeklyDigestEnabled: weeklyDigestEnabled ?? false,
            newSeasonAlerts: newSeasonAlerts ?? true,
            friendActivityAlerts: friendActivityAlerts ?? true,
          },
        });
      } else {
        throw error;
      }
    }

    return NextResponse.json({ preferences });
  } catch (error) {
    console.error('Error updating notification preferences:', error);
    return NextResponse.json(
      { error: 'Failed to update notification preferences' },
      { status: 500 }
    );
  }
}
